---
- name: PULL IMAGE AND START DOCKER CONTAINER
  become: yes
  hosts: all
  tasks:
    - set_fact:
        docker_hosts: "{{  hostvars[item]['ansible_host']  }}"
      loop: "{{ groups['all'] }}"
      run_once: true
    - debug:
         var: docker_hosts

    - name: create directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /srv/gitlab/config
        - /srv/gitlab/data
        - /srv/gitlab/logs


    - name: START CONTAINER
      docker_container:
        name: gitlab-ci
        image: gitlab/gitlab-ce:latest
        env:
          GITLAB_OMNIBUS_CONFIG: |
            external_url 'http://{{ docker_hosts }}'
          GITLAB_ROOT_PASSWORD: 'bgtyhn123$'
        ports:
          - '80:80'
          - '443:443'
          - '2222:22'
        volumes:
          - '/srv/gitlab/config:/etc/gitlab'
          - '/srv/gitlab/logs:/var/log/gitlab'
          - '/srv/gitlab/data:/var/opt/gitlab'
      notify: restart

  handlers:
      - name: restart
        docker_container:
          name: gitlab-ci
          state: started
          restart: yes
