version: '3.3'
services:
  post_db:
    container_name: post_db
    image: mongo:${DBVER}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    container_name: ui
    image: ${USERNAME}/ui:${VER}
    ports:
      - ${UIPORT}
    networks:
      - front_net
  post:
    build: ./post-py
    container_name: post
    image: ${USERNAME}/post:${VER}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    container_name: comment
    image: ${USERNAME}/comment:${VER}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1
  back_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
        gateway: 10.0.2.1
